import type { CoachMarkTour } from '@/types/onboarding.types';

export const tours: Record<string, CoachMarkTour> = {
  'archivadores-tour': {
    id: 'archivadores-tour',
    name: 'Tour de Archivadores',
    description: 'Aprende a gestionar archivadores en el sistema',
    module: 'archivadores',
    steps: [
      {
        id: 'archivadores-create',
        target: '[data-tour="archivadores-create-button"]',
        title: '¡Bienvenido a Archivadores!',
        content: 'Los archivadores son unidades de organización que agrupan expedientes. Comencemos: haz clic en este botón para crear un nuevo archivador.',
        placement: 'left',
        highlightPadding: 8,
      },
      {
        id: 'archivadores-stats',
        target: '[data-tour="archivadores-stats"]',
        title: 'Estadísticas',
        content: 'Aquí visualizas métricas importantes como cantidad de expedientes, documentos totales y estado de ocupación de cada archivador.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'archivadores-search',
        target: '[data-tour="archivadores-search"]',
        title: 'Buscar y Filtrar',
        content: 'Utiliza esta barra para buscar archivadores por código o nombre. Puedes expandir los filtros avanzados para refinar por período, área u oficina.',
        placement: 'bottom',
        highlightPadding: 10,
      },
      {
        id: 'archivadores-table',
        target: '[data-tour="archivadores-table"]',
        title: 'Tabla de Archivadores',
        content: 'Aquí verás todos los archivadores disponibles con su información: código, nombre, período, ubicación física y cantidad de expedientes.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'documentos-tour': {
    id: 'documentos-tour',
    name: 'Tour de Documentos',
    description: 'Descubre cómo gestionar documentos digitales',
    module: 'documentos',
    steps: [
      {
        id: 'documentos-upload',
        target: '[data-tour="documentos-upload-button"]',
        title: '¡Bienvenido a Documentos!',
        content: 'Aquí gestionarás todos los documentos digitales del sistema. Comencemos: usa estos botones para subir documentos individuales o en lote.',
        placement: 'left',
        highlightPadding: 8,
      },
      {
        id: 'documentos-stats',
        target: '[data-tour="documentos-stats"]',
        title: 'Estadísticas y Métricas',
        content: 'Visualiza métricas clave: documentos totales, procesados con OCR, firmados digitalmente y más. Estas estadísticas te ayudan a monitorear el sistema.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'documentos-search',
        target: '[data-tour="documentos-search"]',
        title: 'Búsqueda y Filtros',
        content: 'Busca documentos por número, remitente o contenido. Usa filtros avanzados por archivador, tipo de documento, oficina, firma y fechas.',
        placement: 'bottom',
        highlightPadding: 10,
      },
      {
        id: 'documentos-table',
        target: '[data-tour="documentos-table"]',
        title: 'Tabla de Documentos',
        content: 'Aquí verás todos los documentos con su información: número, tipo, remitente, archivador, fecha y estado de firma. Haz clic en cualquiera para ver detalles.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'expedientes-tour': {
    id: 'expedientes-tour',
    name: 'Tour de Expedientes',
    description: 'Gestiona expedientes y sus documentos asociados',
    module: 'expedientes',
    steps: [
      {
        id: 'expedientes-create',
        target: '[data-tour="expedientes-create-button"]',
        title: '¡Bienvenido a Expedientes!',
        content: 'Los expedientes agrupan documentos relacionados con un mismo asunto o trámite. Comencemos: haz clic aquí para crear un nuevo expediente.',
        placement: 'left',
        highlightPadding: 8,
      },
      {
        id: 'expedientes-stats',
        target: '[data-tour="expedientes-stats"]',
        title: 'Métricas de Expedientes',
        content: 'Visualiza estadísticas clave: total de expedientes, documentos asociados, estados y tendencias. Estas métricas te ayudan a monitorear el sistema.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'expedientes-search',
        target: '[data-tour="expedientes-search"]',
        title: 'Buscar Expedientes',
        content: 'Busca expedientes por código o nombre. La búsqueda es instantánea y te permite encontrar rápidamente el expediente que necesitas.',
        placement: 'bottom',
        highlightPadding: 10,
      },
      {
        id: 'expedientes-table',
        target: '[data-tour="expedientes-table"]',
        title: 'Tabla de Expedientes',
        content: 'Aquí verás todos los expedientes con su información: código, nombre, archivador, cantidad de documentos y fecha. Haz clic en cualquiera para ver detalles.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'general-tour': {
    id: 'general-tour',
    name: 'Tour General del Sistema',
    description: 'Conoce las funcionalidades principales del SAD',
    module: 'general',
    steps: [
      {
        id: 'general-welcome',
        target: '[data-tour="dashboard"]',
        title: '¡Bienvenido al Sistema Integrado de Archivos Digitales!',
        content: 'Este sistema te permite gestionar documentos, expedientes y archivadores de forma digital, con trazabilidad completa y firma digital.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'general-menu',
        target: '[data-tour="sidebar"]',
        title: 'Menú de Navegación',
        content: 'Accede a todas las secciones del sistema desde el menú lateral: Archivo, Consultas, Firmas, Reportes y Administración.',
        placement: 'right',
        highlightPadding: 10,
      },
      {
        id: 'general-search',
        target: '[data-tour="global-search"]',
        title: 'Búsqueda Global',
        content: 'Utiliza la búsqueda global para encontrar rápidamente documentos, expedientes o archivadores en todo el sistema.',
        placement: 'bottom',
        highlightPadding: 8,
      },
      {
        id: 'general-notifications',
        target: '[data-tour="notifications"]',
        title: 'Notificaciones',
        content: 'Recibe alertas sobre documentos que requieren tu firma, cambios en expedientes o actividades importantes del sistema.',
        placement: 'bottom',
        highlightPadding: 8,
      },
      {
        id: 'general-help',
        target: '[data-tour="help-center"]',
        title: 'Centro de Ayuda',
        content: 'Accede al centro de ayuda en cualquier momento para ver guías, FAQs o volver a reproducir este tutorial.',
        placement: 'bottom',
        highlightPadding: 8,
      },
    ],
  },

  'busqueda-tour': {
    id: 'busqueda-tour',
    name: 'Tour de Búsqueda Avanzada',
    description: 'Descubre cómo buscar documentos con filtros potentes',
    module: 'busqueda',
    steps: [
      {
        id: 'busqueda-header',
        target: '[data-tour="search-header"]',
        title: '¡Bienvenido a la Búsqueda Avanzada!',
        content: 'Aquí puedes buscar documentos por texto completo, metadatos, contenido OCR y mucho más. Es la forma más rápida de encontrar lo que necesitas.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'busqueda-saved',
        target: '[data-tour="search-saved"]',
        title: 'Búsquedas Guardadas',
        content: 'Guarda tus búsquedas más frecuentes para aplicarlas con un clic. Perfecto para consultas que haces regularmente como "documentos del mes" o "oficios pendientes".',
        placement: 'bottom',
        highlightPadding: 10,
      },
      {
        id: 'busqueda-search',
        target: '[data-tour="search-input"]',
        title: 'Barra de Búsqueda Principal',
        content: 'Escribe aquí tu consulta. El sistema busca en números de documento, remitentes, contenido OCR procesado y anotaciones. Presiona Enter o clic en Buscar.',
        placement: 'bottom',
        highlightPadding: 8,
      },
      {
        id: 'busqueda-filters',
        target: '[data-tour="search-filters-button"]',
        title: 'Filtros Avanzados',
        content: 'Haz clic en este botón para abrir filtros avanzados: tipo de documento, rango de fechas, oficina, archivador y más. Combínalos para búsquedas precisas.',
        placement: 'left',
        highlightPadding: 8,
      },
      {
        id: 'busqueda-results',
        target: '[data-tour="search-results-table"]',
        title: 'Resultados de Búsqueda',
        content: 'Todos los documentos que coinciden con tu búsqueda aparecen aquí. Puedes ordenar por fecha, número o remitente haciendo clic en los encabezados de columna.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'firma-firmar-tour': {
    id: 'firma-firmar-tour',
    name: 'Tour de Firma Digital',
    description: 'Aprende a firmar documentos digitalmente',
    module: 'firma',
    steps: [
      {
        id: 'firma-wizard-header',
        target: '[data-tour="firma-wizard-header"]',
        title: '¡Bienvenido al Asistente de Firma!',
        content: 'Este asistente te guiará paso a paso para firmar documentos digitalmente con tu certificado de Firma Perú. Es simple y seguro.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'firma-stepper',
        target: '[data-tour="firma-stepper"]',
        title: 'Progreso del Proceso',
        content: 'Sigue el progreso de tu firma: selecciona documento, revisa detalles y firma. Puedes navegar entre pasos usando los botones.',
        placement: 'bottom',
        highlightPadding: 10,
      },
      {
        id: 'firma-search',
        target: '[data-tour="firma-search"]',
        title: 'Buscar Documento',
        content: 'Busca el documento que deseas firmar por nombre, número o remitente. Haz clic en cualquier documento para seleccionarlo.',
        placement: 'bottom',
        highlightPadding: 8,
      },
      {
        id: 'firma-checklist',
        target: '[data-tour="firma-checklist"]',
        title: 'Checklist de Requisitos',
        content: 'Verifica que cumples todos los requisitos: token USB conectado, drivers instalados y certificado vigente antes de firmar.',
        placement: 'left',
        highlightPadding: 10,
      },
    ],
  },

  'firma-flujos-tour': {
    id: 'firma-flujos-tour',
    name: 'Tour de Flujos de Firma',
    description: 'Gestiona flujos de firma colaborativos',
    module: 'firma',
    steps: [
      {
        id: 'firma-flujos-header',
        target: '[data-tour="firma-flujos-header"]',
        title: '¡Bienvenido a Flujos de Firma!',
        content: 'Los flujos permiten que múltiples personas firmen un documento en orden secuencial. Ideal para aprobaciones y autorizaciones.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'firma-flujos-create',
        target: '[data-tour="firma-flujos-create"]',
        title: 'Crear Nuevo Flujo',
        content: 'Haz clic aquí para crear un flujo de firma. Define el documento, los firmantes y el orden de firma.',
        placement: 'left',
        highlightPadding: 8,
      },
      {
        id: 'firma-flujos-stats',
        target: '[data-tour="firma-flujos-stats"]',
        title: 'Estadísticas de Flujos',
        content: 'Visualiza métricas importantes: flujos totales, en progreso, completados y cancelados para monitorear el estado general.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'firma-flujos-filters',
        target: '[data-tour="firma-flujos-filters"]',
        title: 'Filtros de Búsqueda',
        content: 'Filtra flujos por estado, fechas o firmantes para encontrar rápidamente lo que buscas.',
        placement: 'bottom',
        highlightPadding: 10,
      },
      {
        id: 'firma-flujos-table',
        target: '[data-tour="firma-flujos-table"]',
        title: 'Tabla de Flujos',
        content: 'Todos los flujos de firma con su información: nombre, documento, estado, firmantes y progreso. Haz clic en cualquiera para ver detalles.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'firma-validar-tour': {
    id: 'firma-validar-tour',
    name: 'Tour de Validación de Firmas',
    description: 'Verifica la autenticidad de firmas digitales',
    module: 'firma',
    steps: [
      {
        id: 'firma-validar-header',
        target: '[data-tour="firma-validar-header"]',
        title: '¡Bienvenido a Validación de Firmas!',
        content: 'Aquí puedes verificar la autenticidad y validez de firmas digitales en documentos. Selecciona un documento desde la lista de documentos o desde el módulo de archivo para validar sus firmas.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'firma-validar-tabs',
        target: '[data-tour="firma-validar-tabs"]',
        title: 'Opciones de Validación',
        content: 'Una vez que selecciones un documento, podrás elegir entre validación interna (rápida, del sistema), externa (oficial de Firma Perú) o revisar el historial completo de validaciones.',
        placement: 'bottom',
        highlightPadding: 10,
      },
    ],
  },

  'firma-analytics-tour': {
    id: 'firma-analytics-tour',
    name: 'Tour de Analítica de Firmas',
    description: 'Consulta estadísticas y métricas de uso',
    module: 'firma',
    steps: [
      {
        id: 'firma-analytics-header',
        target: '[data-tour="firma-analytics-header"]',
        title: '¡Bienvenido a Analítica de Firma!',
        content: 'Aquí encontrarás métricas detalladas sobre el uso del sistema de firma digital: tendencias, distribución y top firmantes.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'firma-analytics-filters',
        target: '[data-tour="firma-analytics-filters"]',
        title: 'Filtros de Período',
        content: 'Selecciona el rango de fechas para ver estadísticas específicas. Puedes usar presets o elegir fechas personalizadas.',
        placement: 'bottom',
        highlightPadding: 10,
      },
      {
        id: 'firma-analytics-metrics',
        target: '[data-tour="firma-analytics-metrics"]',
        title: 'Métricas Principales',
        content: 'Visualiza métricas clave: total de firmas, promedio diario, documentos firmados, tasa de adopción y tiempo promedio de flujos.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'firma-analytics-trend',
        target: '[data-tour="firma-analytics-trend"]',
        title: 'Tendencia de Firmas',
        content: 'Este gráfico muestra la evolución de firmas a lo largo del tiempo. Identifica picos de actividad y tendencias de uso.',
        placement: 'top',
        highlightPadding: 12,
      },
      {
        id: 'firma-analytics-charts',
        target: '[data-tour="firma-analytics-charts"]',
        title: 'Distribución y Top Firmantes',
        content: 'Analiza la distribución de firmas por tipo de documento y los usuarios más activos del sistema.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'reportes-intro-tour': {
    id: 'reportes-intro-tour',
    name: 'Introducción a Reportes',
    description: 'Conoce las funcionalidades principales del módulo de reportes',
    module: 'reportes',
    steps: [
      {
        id: 'reportes-header',
        target: '[data-tour="reportes-header"]',
        title: '¡Bienvenido al Módulo de Reportes!',
        content: 'Aquí puedes generar reportes detallados sobre documentos, actividad de usuarios y firmas digitales del sistema.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'reportes-guided-tour',
        target: '[data-tour="reportes-guided-tour"]',
        title: 'Tours Específicos',
        content: 'Usa este menú para acceder a tours detallados de cada tipo de reporte: documentos, actividad y firmas. Cada tour te guiará cuando generes datos.',
        placement: 'left',
        highlightPadding: 8,
      },
      {
        id: 'reportes-filters',
        target: '[data-tour="reportes-filters"]',
        title: 'Generar tu Primer Reporte',
        content: 'Selecciona el tipo de reporte, ajusta el rango de fechas y haz clic en "Generar Reporte". Una vez generado, podrás exportarlo en PDF, Excel o CSV.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'reportes-documentos-tour': {
    id: 'reportes-documentos-tour',
    name: 'Reporte de Documentos',
    description: 'Analiza estadísticas y tendencias de documentos',
    module: 'reportes',
    steps: [
      {
        id: 'reportes-doc-summary',
        target: '[data-tour="reportes-doc-summary"]',
        title: 'Resumen de Documentos',
        content: 'Visualiza métricas clave: total de documentos, folios, distribución por tipo y estado de firma en el período seleccionado.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'reportes-doc-charts',
        target: '[data-tour="reportes-doc-charts"]',
        title: 'Gráficos de Distribución',
        content: 'Analiza la distribución de documentos por tipo y oficina. Identifica patrones de uso y áreas más activas.',
        placement: 'top',
        highlightPadding: 12,
      },
      {
        id: 'reportes-doc-trend',
        target: '[data-tour="reportes-doc-trend"]',
        title: 'Tendencia Temporal',
        content: 'Observa cómo evoluciona la cantidad de documentos mes a mes. Identifica picos de actividad y tendencias estacionales.',
        placement: 'top',
        highlightPadding: 12,
      },
      {
        id: 'reportes-doc-table',
        target: '[data-tour="reportes-doc-table"]',
        title: 'Detalle por Tipo',
        content: 'Consulta el detalle de documentos agrupados por tipo con cantidades y folios. Puedes ordenar por cualquier columna.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'reportes-actividad-tour': {
    id: 'reportes-actividad-tour',
    name: 'Reporte de Actividad',
    description: 'Monitorea el uso del sistema por usuarios',
    module: 'reportes',
    steps: [
      {
        id: 'reportes-act-summary',
        target: '[data-tour="reportes-act-summary"]',
        title: 'Resumen de Actividad',
        content: 'Visualiza métricas de uso: acciones totales, usuarios únicos, promedio de actividad y trazabilidad completa.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'reportes-act-module',
        target: '[data-tour="reportes-act-module"]',
        title: 'Actividad por Módulo',
        content: 'Identifica qué módulos del sistema son más utilizados: Archivo, Firma, Consultas o Reportes.',
        placement: 'top',
        highlightPadding: 12,
      },
      {
        id: 'reportes-act-trend',
        target: '[data-tour="reportes-act-trend"]',
        title: 'Tendencia Diaria',
        content: 'Observa la actividad día a día. Identifica horarios pico y días de mayor uso del sistema.',
        placement: 'top',
        highlightPadding: 12,
      },
      {
        id: 'reportes-act-users',
        target: '[data-tour="reportes-act-users"]',
        title: 'Usuarios Más Activos',
        content: 'Consulta el ranking de usuarios con mayor actividad. Útil para identificar usuarios clave y patrones de uso.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'reportes-firmas-tour': {
    id: 'reportes-firmas-tour',
    name: 'Reporte de Firmas',
    description: 'Analiza el uso de firma digital',
    module: 'reportes',
    steps: [
      {
        id: 'reportes-sig-summary',
        target: '[data-tour="reportes-sig-summary"]',
        title: 'Resumen de Firmas',
        content: 'Métricas clave de firma digital: total de firmas, documentos firmados, firmantes únicos y distribución por estado.',
        placement: 'bottom',
        highlightPadding: 12,
      },
      {
        id: 'reportes-sig-charts',
        target: '[data-tour="reportes-sig-charts"]',
        title: 'Top Firmantes y Estados',
        content: 'Visualiza los usuarios más activos en firma digital y la distribución de firmas por estado (válidas, pendientes, revertidas).',
        placement: 'top',
        highlightPadding: 12,
      },
      {
        id: 'reportes-sig-trend',
        target: '[data-tour="reportes-sig-trend"]',
        title: 'Tendencia de Firmas',
        content: 'Observa la evolución temporal de firmas digitales. Identifica adopción del sistema y patrones de uso.',
        placement: 'top',
        highlightPadding: 12,
      },
      {
        id: 'reportes-sig-table',
        target: '[data-tour="reportes-sig-table"]',
        title: 'Detalle de Firmantes',
        content: 'Consulta el ranking completo de firmantes con totales. Puedes exportar esta información para análisis detallado.',
        placement: 'top',
        highlightPadding: 12,
      },
    ],
  },

  'configuracion-tour': {
    id: 'configuracion-tour',
    name: 'Tour de Configuración',
    description: 'Personaliza el sistema con tu marca corporativa',
    module: 'configuracion',
    steps: [
      {
        id: 'configuracion-general',
        target: '[data-tour="configuracion-general"]',
        title: '¡Bienvenido a Configuración!',
        content: 'Aquí puedes personalizar el sistema con tu información corporativa: nombre de empresa, slogan, colores y datos de contacto.',
        placement: 'right',
        highlightPadding: 12,
      },
      {
        id: 'configuracion-branding',
        target: '[data-tour="configuracion-branding"]',
        title: 'Marca Corporativa',
        content: 'Sube tu logo corporativo para que aparezca en la barra de navegación, reportes y exportaciones. También puedes configurar un sello para las firmas digitales.',
        placement: 'right',
        highlightPadding: 12,
      },
      {
        id: 'configuracion-firma',
        target: '[data-tour="configuracion-firma"]',
        title: 'Configuración de Firma',
        content: 'Activa o desactiva el uso del sello corporativo en las firmas digitales. Cuando está activo, el sello configurado se incluirá automáticamente en todos los documentos firmados.',
        placement: 'right',
        highlightPadding: 12,
      },
    ],
  },
};

export function getTour(tourId: string): CoachMarkTour | undefined {
  return tours[tourId];
}

export function getToursByModule(module: CoachMarkTour['module']): CoachMarkTour[] {
  return Object.values(tours).filter((tour) => tour.module === module);
}
